name: CI (API Schema)

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  format-tsp:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Setup
        uses: ./.github/composite-actions/cache-and-install

      - name: Check formatting for TypeSpec
        working-directory: ./packages/api-schema
        shell: bash
        run: |
          pnpm run format:tsp:check

